"""empty message

Revision ID: 9422fa2ca6f0
Revises: 5f81f7ea8d3d
Create Date: 2022-10-17 17:30:18.043092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9422fa2ca6f0'
down_revision = '5f81f7ea8d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nick_name', sa.String(length=200), nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('user', 'nick_name')
    # ### end Alembic commands ###
